s_zhachek_homework_6_complete
eugene-okulik/QAP-08onl pull request #101
Opened 2022-06-16 16:05 UTC by SiarheiZhachek

2022-06-18 09:13 UTC, eugene-okulik requested changes

2022-06-18 09:13 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_6/calculator.py
> +                result = a_a / b_b
Результатом деления должны быть частное и остаток

2022-06-18 09:13 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_6/number_of_letters.py
> +print(RESULT.replace('1', ''))
Даже для той строки, которая используется у тебя, результат неправильный. Сейчас результат "cea3d3", а должен быть "a3d3ce".
Когда будешь исправшять, пробуй еще не строке "abeehhhhhccced"

2022-06-18 09:13 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_6/price_list.py
> +print(MY_DICT)
Это задание ок.

2022-06-22 09:01 UTC, eugene-okulik requested changes
Ты создал папку "Домашнее задание" и поместил туда два из своих файлов. Выполнение этой ДЗ должно лежать в /homework/siarhei_zhachek/homework_6

2022-06-22 09:08 UTC, eugene-okulik commented
И кстати рекомендация в целом - страрайся никогда не называть файлы и папки не латинскими символами и не используй пробелы в этих именах. У очень многих программ есть с этим проблемы.

2022-06-22 19:14 UTC, SiarheiZhachek commented
теперь вроде правильно.

2022-06-24 16:41 UTC, eugene-okulik approved these changes

2022-06-24 16:41 UTC, merged