Homework7 done
eugene-okulik/QAP-08onl pull request #103
Opened 2022-06-18 15:42 UTC by stassia92

Добавила домашку №7

2022-06-21 16:35 UTC, eugene-okulik requested changes

2022-06-21 16:46 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/homework7/homework7_2.py
> +    if user_input_date == CORRECT_DATE and entered_code == "123":
А еще у тебя существует константа CORRECT_CODE, но ты ей не пользуешься, а зря

2022-06-21 19:03 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework7/homework7_2.py
> +CORRECT_DATE = now.strftime("%B %d, %Y")
исправила задание на более легкий вариант. не получается исправить вместе с вводом пользователя слишком за мудрено.

2022-06-21 19:51 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework7/homework7_2.py
> +    if user_input_date == CORRECT_DATE and entered_code == "123":
> Вот здесь ты проверяешь `user_input_date == CORRECT_DATE`. В итоге, получается, что действительны только те купоны, у которых expiration date - сегодня. Если они истекают завтра, то программа говорит, что купон недействителен.

исправила

2022-06-22 09:04 UTC, eugene-okulik approved these changes

2022-06-22 09:04 UTC, merged