Wolk homework 7
eugene-okulik/QAP-08onl pull request #107
Opened 2022-06-19 12:23 UTC by Sergey1991wolk

homework_done

2022-06-21 16:54 UTC, eugene-okulik requested changes

2022-06-21 16:54 UTC, eugene-okulik commented on homework/wolk/wolk_sergey_homework_7/hwork_1.py
> +    print(f'Расшифрованное сообщение: {decryption_caesar(ENCRYPTED_MESSAGE):f}')
Вот что сейчас выдает программа:
```
Traceback (most recent call last):
  File "/home/eugene/projects/QAP-08onl/homework/wolk/wolk_sergey_homework_7/hwork_1.py", line 44, in <module>
    print(f'Введите Сообщение: {MESS:f}')
ValueError: Unknown format code 'f' for object of type 'str'
```

2022-06-21 16:54 UTC, eugene-okulik commented on homework/wolk/wolk_sergey_homework_7/hwork_2.py
> +K_DATE = DATE.strftime('%B %d, %Y')
А вот здесь ты преобразуешь дату, которая в понятном для питона формате в дату, которая понятна человеку, но непонятна питону. В итоге ты не сможешь сравнить даты с помощью ">" или "<".
Нужно наоборот преобразовать дату, которую ввел пользователь в понятный формат для питона (с помощью strptime), и тогда ты сможешь нормально сравнивать эти даты.

2022-06-21 16:54 UTC, eugene-okulik commented on homework/wolk/wolk_sergey_homework_7/hwork_2.py
> +    if _entered_code == CODE and _expiration_date == K_DATE:
Вот здесь ты проверяешь `_expiration_date == K_DATE`. В итоге, получается, что действительны только те купоны, у которых expiration date - сегодня. Если они истекают завтра, то программа говорит, что купон недействителен.

2022-06-22 11:33 UTC, Sergey1991wolk commented on homework/wolk/wolk_sergey_homework_7/hwork_1.py
> +    print(f'Расшифрованное сообщение: {decryption_caesar(ENCRYPTED_MESSAGE):f}')
починил)

2022-06-22 12:26 UTC, eugene-okulik requested changes

2022-06-22 12:26 UTC, eugene-okulik commented on homework/wolk/wolk_sergey_homework_7/hwork_1.py
> +    print(f'Расшифрованное сообщение: {decryption_caesar(ENCRYPTED_MESSAGE):}')
тут все ок теперь

2022-06-22 12:26 UTC, eugene-okulik commented on homework/wolk/wolk_sergey_homework_7/hwork_2.py
> +print(check_coupon(_entered_code, _expiration_date))
а тут купон с будущей датой считается недействительным
```
Введите номер купона: 123
Введите дату в формате (Month name DD, YYYY): July 12, 2022            
False
```

2022-06-22 12:29 UTC, Sergey1991wolk commented on homework/wolk/wolk_sergey_homework_7/hwork_2.py
> +print(check_coupon(_entered_code, _expiration_date))
Ой.. почти почти... попробую что то сделать

2022-06-26 08:11 UTC, eugene-okulik approved these changes

2022-06-26 08:12 UTC, merged