anastasia_machkova_homework_8
eugene-okulik/QAP-08onl pull request #119
Opened 2022-06-22 21:21 UTC by machkova98

2022-06-26 07:10 UTC, eugene-okulik requested changes

2022-06-26 07:10 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_8/task_2.py
> +print(sorted(number_names, key=lambda x: x))
Сейчас программа сортирует список чисел по их значению. А должна сортировать по их названию. Т.е. 0 будет где-то в конце, т.к. его название начинается на "z".
Ну и сортировать нужно не словарь, а какой-то список чисел (например, полученный от пользователя)

2022-07-09 08:52 UTC, machkova98 commented on homework/Anastasia_Machkova/Homework_8/task_2.py
> +print(sorted(number_names, key=lambda x: x))
я уже не буду исправлять. Спасибо!

2022-07-10 09:10 UTC, eugene-okulik approved these changes

2022-07-10 09:10 UTC, merged