nikolay nazarov: homework 9 completed
eugene-okulik/QAP-08onl pull request #123
Opened 2022-06-23 16:37 UTC by nazarovNV

2022-06-26 08:52 UTC, eugene-okulik requested changes

2022-06-26 08:52 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_9/task_1.py
> +        return Book._who_reserve_book_dict
Все статик методы явно относятся к еще одному типу объекта. Например, библиотека. Хотя можно обойтись и без библиотеки, а просто хранить в экземпляре объекта `Book` пользователя, который взял эту книгу.
Ну и ты передаешь в некоторые статик методы `book`, хотя мог бы передавать `self`, и тогда эти методы были бы не статик, но и работали бы только для той книги, для которой этот метод вызван.

2022-06-26 08:52 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_9/task_2.py
> +        pass
Эти пустые методы можно было не создавать, т.к. в этом классе должен находиться метод, который считает доходность именно этой инвестиции. Идея в том, что экземпляров инвестиции может быть много. И у каждой свои условия. Например, у каждой может быть разный процент.

2022-06-26 08:52 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_9/task_2.py
> +        pass
а класс банк мог бы иметь функцию, которая запрашивает результат расчета из ивестиции - и возвращает его

2022-06-26 15:23 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_9/task_1.py
> +        return Book._who_reserve_book_dict
Я решил статики брать чтобы поупражняться с сокрытием данных. Я хотел чтобы читатель не мог изменять поля в книге.

2022-06-26 15:24 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_9/task_2.py
> +        pass
В задании же написано что у банка метод депозит. В итоге и в инвестиции и в банке должен быть метод расчета доходности? Зачем?

2022-07-02 07:30 UTC, eugene-okulik approved these changes

2022-07-02 07:30 UTC, merged