Artyom zabello homework 9 is done
eugene-okulik/QAP-08onl pull request #126
Opened 2022-06-25 12:44 UTC by Lanselap1488

Первую задачу делал до 5 утра почти)

2022-06-26 09:02 UTC, eugene-okulik requested changes

2022-06-26 09:02 UTC, eugene-okulik commented on homework/artyom_zabello/homework_9/task1.py
> +        self.reserved_books = reserved_books
Идея в том, что не класс пользователя хранит инфу о забронированных книгах, а класс книги хранит инфу о том, какой пользователь забронил книгу. Таким образом, когда другой пользователь обратится за книгой, то класс книги вернет информацию о том, что книга забронирована и оттуда же можно будет получить инфу кем она забронирована.
А сейчас получается, что книга только знает, что она забронирована, но не знает кем.

2022-06-26 09:02 UTC, eugene-okulik commented on homework/artyom_zabello/homework_9/task2.py
> +        pass
В класс банк можно добавить экземпляр инвестиции. Тогда класс банк сможет получать из нее профит без статик метода, а из инвестиции, которая в нем хранится

2022-06-27 22:08 UTC, Lanselap1488 commented
Поправил первую задачу, теперь пишет у кого какая книга, но в классе юзер, а не в классе книг, надеюсь ниче страшного?)

2022-07-02 07:37 UTC, eugene-okulik commented
> Поправил первую задачу, теперь пишет у кого какая книга, но в классе юзер, а не в классе книг, надеюсь ниче страшного?)

Оно то ничего страшного в плане тренировки работы с классами. Но оно бессмысленно по логике. Существует у кого-то книга. Он ее кому-то отдал. И все, что он знает о своей книге - это то, что она у кого-то. Для того, чтобы узнать у кого она конкретно, ему надо пойти у каждого пользователя спросить какие у него книги.

2022-07-02 07:43 UTC, eugene-okulik approved these changes

2022-07-02 07:43 UTC, merged