stassia92 homework10 done
eugene-okulik/QAP-08onl pull request #131
Opened 2022-06-27 13:04 UTC by stassia92

Добавила 10 домашку! Пришлось в класс цветов добавить 2 пустых публичных метода. по другому не смогла решить эту проблему

2022-07-03 07:59 UTC, eugene-okulik requested changes

2022-07-03 07:59 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        pass
Родительский класс существует для того, чтобы задавать структуру всех дочерних классов. Поэтому в нем должен быть метод init(flower_name=None, color=None, .....)
Затем, при инициализации каждого дочернего класса нужно вызывать super().init(flower_name='Rose', color='Red', .....)

2022-07-03 07:59 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        self.stem_length = 75
Розы не все белые, поэтому можно при инициализации класса дать возможность указать цвет.
И цена каждого цветка может отличаться от цены по-умолчанию - тоже можно дать возможность указать цену при создании.
Также, можно создать методы, позволяющие изменять цену цветка, его цвет.
Эти методы можно реализовать для всех цветов, в родительском классе. Тогда и пайлинт перестанет ругаться

2022-07-03 07:59 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        return res
Эта функция могла бы соделжать одну строчку `return len(self.components)`

2022-07-03 11:27 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        pass
исправлено

2022-07-03 11:27 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        self.stem_length = 75
добавила 2 сеттера на цвет и цену

2022-07-03 11:28 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        return res
изменила

2022-07-03 17:22 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/homework10/homework10.py
> +        pass
добавила кваргс для самообучения. в случаях если много аргументов в свойствах. чтобы использовать на будущее)

2022-07-06 17:35 UTC, eugene-okulik approved these changes
Ну да, здесь у тебя 5 аргументов - можно было и без кваргсов, но вообще решение хорошее.

2022-07-06 17:35 UTC, merged