Artyom zabello homework 10
eugene-okulik/QAP-08onl pull request #136
Opened 2022-06-28 21:40 UTC by Lanselap1488

2022-07-03 08:09 UTC, eugene-okulik requested changes

2022-07-03 08:09 UTC, eugene-okulik commented on homework/artyom_zabello/homework_10/task.py
> +        self.name = 'Chamomile'
Можно создать методы, позволяющие изменять цену цветка, его цвет.
Эти методы можно реализовать для всех цветов, в родительском классе. Тогда и пайлинт перестанет ругаться и не надо будет делать пустые методы

2022-07-04 11:24 UTC, Lanselap1488 commented on homework/artyom_zabello/homework_10/task.py
> +        self.name = 'Chamomile'
Добпвил) Спасибо за идею)

2022-07-10 09:28 UTC, eugene-okulik approved these changes

2022-07-10 09:29 UTC, merged