Anastasiya_Botukh_homework_9
eugene-okulik/QAP-08onl pull request #139
Opened 2022-07-01 11:11 UTC by Aisatsanaaa

2022-07-01 11:17 UTC, Aisatsanaaa commented
если честно, не понимаю, на что пайлинт ругается (

2022-07-02 08:21 UTC, eugene-okulik requested changes

2022-07-02 08:21 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_9/ht_1.py
> +    def __init__(self, name, author, pages, isbn, reserved, taken):
Здесь он ругается, что слишком много аргументов
Для создания экземпляра кники достаточно ее имени, автора, страниц, и кода isbn.
Флаги reserved и taken могут быть установлены по умолчанию как  False.

2022-07-02 08:21 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_9/ht_2.py
> +        self.term = term
В этот класс нужно добавить функцию, которая расчитывает доходность инвестиции

2022-07-02 08:21 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_9/ht_2.py
> +class Bank:
В этот класс нужно добавить функцию __init__, которая инициализирует хранение инвестиции внутри класса Bank

2022-07-02 08:21 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_9/ht_2.py
> +        return total_amount
А эта функция может просто возвращать расчет инвестиции, посчитанный в классе Investment (из экземпляра инвестиции, добавленного в Банк).

2022-07-02 08:21 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_9/ht_1.py
> +user_1.return_book(book_3)
А в целом, решение хорошее. Только с пайлинтом разобраться.

2022-07-06 17:41 UTC, merged