Max tsybulka Complete homework
eugene-okulik/QAP-08onl pull request #15
Opened 2022-05-30 19:05 UTC by maxtsybulka

Complete homework

2022-05-30 20:04 UTC, eugene-okulik requested changes
Каких - то .DS_Store от тебя налетело. Если сможешь избавиться от них, было бы круто.
И файл пустой находится не в твоей папке, а в общей папке homework

2022-05-31 09:59 UTC, eugene-okulik commented
А, я допер. Это ты вместо пустого файла добавил ридми. Ну сойдет. 
Но попробуй избавиться от этих .DS_Store. Если не получится - говори. Я сам почищу.

2022-06-02 13:25 UTC, eugene-okulik commented
Переименуй папку homework_max_tsybulka в max_tsybulka
И два .DS_Store еще осталось

2022-06-02 13:44 UTC, maxtsybulka commented
@eugene-okulik  удалил файлы .DS_Store. Можно проверять)

2022-06-02 13:49 UTC, eugene-okulik commented
Красота. Осталось только переименовать папку homework_max_tsybulka в max_tsybulka

2022-06-02 15:32 UTC, eugene-okulik approved these changes

2022-06-02 15:32 UTC, merged