anastasia_machkova_Homework_10_done
eugene-okulik/QAP-08onl pull request #164
Opened 2022-07-10 21:38 UTC by machkova98

Только у меня не получилось expiration_date

2022-07-10 21:43 UTC, machkova98 commented
не пойму на что он ругается

2022-07-16 07:38 UTC, eugene-okulik requested changes

2022-07-16 07:38 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_10/task_1.py
> +            result + flower.expiration_date / 4
Он ругается на то, что результат этой операции никуда не сохраняется (ни в какую переменную), а значит не может быть никак использован. Скорее всего, ты хотела здесь сделать `+=`

2022-07-31 06:50 UTC, eugene-okulik approved these changes

2022-07-31 06:51 UTC, merged