homework_3_varvara_kirylchyk_done
eugene-okulik/QAP-08onl pull request #17
Opened 2022-05-30 19:42 UTC by Kirylchyk

homework_3_varvara_kirylchyk_done

2022-05-30 19:58 UTC, eugene-okulik requested changes
После выполнения ДЗ по Git в репозитории есть папка homework/varvara_kirylchyk/
А в этом задании ты создала в папке homework еще одну папку Homework_kirylchyk_3
Перемести эту новую папку в уже существующую папку varvara_kirylchyk

2022-05-30 19:58 UTC, eugene-okulik commented on homework/Homework_kirylchyk_3/varvara_kirylchyk_homework_3_01.py
> +a=1
Проверка форматирования считает эти переменные константами и требует, чтобы они были написаны большими буквами
Весь список ошибок можно посмотреть вот здесь https://github.com/eugene-okulik/QAP-08onl/pull/17/checks

2022-05-30 19:58 UTC, eugene-okulik commented on homework/Homework_kirylchyk_3/varvara_kirylchyk_homework_3_03.py
> +
Лишняя пустая строка. Но это тоже есть в ошибках форматирования (https://github.com/eugene-okulik/QAP-08onl/pull/17/checks)

2022-05-30 19:58 UTC, eugene-okulik commented on homework/Homework_kirylchyk_3/varvara_kirylchyk_homework_3_05.py
> +#Программа запрашивает у пользователя длину ребра куба. И находит объем куба и площадь его боковой поверхности
Слишком длинная строка

2022-05-30 19:58 UTC, eugene-okulik commented on homework/Homework_kirylchyk_3/varvara_kirylchyk_homework_3_05.py
> +
Много пустых строк

2022-05-31 00:30 UTC, Kirylchyk commented on homework/Homework_kirylchyk_3/varvara_kirylchyk_homework_3_01.py
> +a=1
что-то с константами не поняла...

2022-05-31 06:52 UTC, eugene-okulik commented
Ты для внесенных изменений создала новый полу реквест. Я тогда этот первый закрою - и будем продолжать обсуждение в новом

2022-05-31 06:52 UTC, closed without merging