Artyom zabello homework 3
eugene-okulik/QAP-08onl pull request #19
Opened 2022-05-30 21:37 UTC by Lanselap1488

artyom zabello: homework 3 completed

2022-05-31 07:20 UTC, eugene-okulik requested changes
Все хорошо. Особенно порадовало, что ты исправил те вещи, которые нашел Pylint в форматировании.
Нужно исправить только одну вещь, но во всей работе. Нужно, чтобы операторы (+, -, *, **, /, =, ...) были окружены пробелами. Pycharm и Pylint на это не обращают внимания, но правило такое есть (https://www.flake8rules.com/rules/E225.html).

2022-05-31 07:20 UTC, eugene-okulik commented on homework/artyom_zabello/Homework_3/task3.py
> +RES1 = (NUM+NUM1) / 2
Операторы типа + нужно окружать пробелами

2022-05-31 08:16 UTC, Lanselap1488 commented on homework/artyom_zabello/Homework_3/task3.py
> +RES1 = (NUM+NUM1) / 2
Мне нужно отменить пулл ревест и создать новый?

2022-05-31 11:48 UTC, eugene-okulik commented on homework/artyom_zabello/Homework_3/task3.py
> +RES1 = (NUM+NUM1) / 2
Да, спасибо, что обратил внимание.
В эти детали не доводилось залазить. Вижу, что к арифметическим операторам в целом свободный подход используется и рекомендуется использовать то, что кажется удобным. И вижу, что рекомендуют не ставит пробелы когда выражение идет в скобках.

2022-05-31 11:50 UTC, eugene-okulik commented on homework/artyom_zabello/Homework_3/task3.py
> +RES1 = (NUM+NUM1) / 2
Тогда все ок.
А если бы нужно было что-то исправлять, то исправляешь в той же ветке и коммитишь - оно автоматически попадет в этот пул реквест.
Пока не буду его закрывать. Если хочешь, можешь попробовать

2022-06-01 07:11 UTC, eugene-okulik approved these changes

2022-06-03 08:18 UTC, merged