nikolay nazarov: homework 20 completed
eugene-okulik/QAP-08onl pull request #244
Opened 2022-08-13 20:35 UTC by nazarovNV

2022-08-24 06:08 UTC, eugene-okulik requested changes

2022-08-24 06:08 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_20/task_2.py
> +chrome_driver.quit()
Тест падает с ошибкой:
```
E   selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class=" css-2b097c-container" id="state">...</div> is not clickable at point (874, 891). Other element would receive the click: <iframe id="google_ads_iframe_/21849154601,22343295815/Ad.Plus-Anchor_0" name="google_ads_iframe_/21849154601,22343295815/Ad.Plus-Anchor_0" title="3rd party ad content" width="728" height="90" scrolling="no" marginwidth="0" marginheight="0" frameborder="0" role="region" aria-label="Advertisement" tabindex="0" sandbox="allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-top-navigation-by-user-activation" style="border: 0px; vertical-align: bottom;" data-load-complete="true" data-google-container-id="1"></iframe>
```
Я писал в чате как оойти этй проблему - нужно изменить размер окна браузера, тогда вид сайта немного изменяется и все элементы становятся доступными.

2022-08-24 06:08 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_20/task_1.py
> +chrome_driver.quit()
Здесь покликал не по всем чекбоксам. Некоторые `>` не открыл, но можно не исправлять. Там код будет аналогичный существующему.

2022-08-28 12:23 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_20/task_2.py
> +chrome_driver.quit()
У меня не падает тест, отправил видео в личку

2022-08-28 12:23 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_20/task_1.py
> +chrome_driver.quit()
Поправил

2022-08-29 05:51 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_20/task_2.py
> +chrome_driver.quit()
Ну да. Видимо, ты запускаешь на большом экране

2022-08-29 05:51 UTC, eugene-okulik approved these changes

2022-08-29 05:51 UTC, merged