varvara_kirylchyk_homework21
eugene-okulik/QAP-08onl pull request #246
Opened 2022-08-14 16:25 UTC by Kirylchyk

some work done

2022-08-24 17:13 UTC, eugene-okulik requested changes
Получилось как-то много комментов. Основное:
- фикстура должна полностью вмещать в себя настройку драйвера. И фикстура, настраивающая драйвер должна иметь возможность запускаться вместе с каждым UI тестом, т.к. каждый тест должен быть независим. Т.е. если запустили только один тест, то он должен иметь возможность запуститься. Это можно сделать и не перезапуская браузер для каждого теста, но тест должен знать название фикстуры, которая его запускает.
- Слипы дожны использоваться только тогда, когда никакое ожидание не помогает.

2022-08-24 17:13 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_3.py
> +    time.sleep(3)
Все эти тесты должны были быть одним тестом с проверкой в конце что текст “All Buttons Clicked” появился на экране

2022-08-24 17:13 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_4.py
> +    time.sleep(5)
Вместо этого слипа нужно было сделать ожидание. Слипы используются только тогда, когда никаким ожиданием проблему не решить.

2022-08-25 15:03 UTC, Kirylchyk commented
Спасибо! Подправила. У меня тока эта ошибка, не надумала как ее устранить
W0621: Redefining name '.....' from outer scope (line ....) (redefined-outer-name)

2022-08-29 06:14 UTC, eugene-okulik requested changes
В целом, все поправила хорошо. Осталось пара нюансов.

2022-08-29 06:14 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_1.py
> +def test_sum7(print_text, num1, num2):
Здесь в параметрах ты создаешь в параметрах переменные 'a, b', а в тесте ожидаешь переменные um1, num2 и теперь ничего не работает ))

2022-08-29 06:14 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_1.py
> +@pytest.mark.hard
При запуске тестов появляются ворнинги про эти метки `hard` и `simple`. Прямо в ворнинге есть ссылка на страницу, где написано как от этого избавиться (ну и на занятии я рассказывал).

2022-08-29 06:14 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_3.py
> +    setup.implicitly_wait(5)
Ты сделала включение неявного ожидания в фикстуре (и это правильно). Больше его можно не включать. Оно будет оставаться включенным пока не сделаешь driver.quit()

2022-08-29 06:16 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_1.py
> +import pytest as pytest
И вот еще на это пайлинт ругается. тут нужно просто `import pytest`

2022-08-31 06:35 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework21/test_varvara_kirylchyk_homework21_1.py
> +@pytest.mark.parametrize('a, b', [[1, 2], [3, 4], [5, 6]])
Блин, хотел уже закрыть, но в пайлинте есть теперь еще одна штука:
```
Argument name "a" doesn't conform to snake_case naming style (invalid-name)
```

2022-08-31 06:36 UTC, eugene-okulik requested changes
Поправь эти названия переменных - и закроем уже это задание

2022-09-01 05:06 UTC, eugene-okulik approved these changes

2022-09-01 05:12 UTC, merged