Tatiana Molofei Added Task_1 from Homework_21
eugene-okulik/QAP-08onl pull request #256
Opened 2022-08-17 18:35 UTC by tmolofei

2022-08-24 23:30 UTC, tmolofei commented
Мне нужна помощь с 5 тестом( он почему то даже не запускается

2022-08-25 11:47 UTC, eugene-okulik requested changes

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_01.py
> +    print("\nAfter every test\n")
Фикстуры не запускаются. ни перед всеми тестами ни перед каждым.
![2022-08-25_14-30](https://user-images.githubusercontent.com/98970620/186653303-31a19bab-8d76-4ecb-88aa-7cfaa9611032.png)

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +
Эти три строчки должны быть в фикстуре - там происходит вся настройка драйвера

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +    # driver.quit()
Забыла вернуть назад закрытие браузера

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +    driver.get('http://automationpractice.com/index.php')
Открытие страницы - дело теста, для которого эта страница нужна.

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +    text_at_end_page = driver.find_element(By.XPATH, '//section[@class="bottom-footer col-xs-12"]')
В результате работы фикстуры возвращается драйвер - вот им и нужно пользоваться.

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +def test_title_woman_page_is_displayed():
Каждый тест должен быть независимым. Этот тест невозможно запустить если перед ним не был запущен тест `test_text_at_end_page`

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +    assert driver.find_element(By.ID, 'header_logo').is_displayed()
Три теста с логотипом можно объединить в один.

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +    driver.implicitly_wait(10)
Неявное ожидание включается один раз. Обычно это делается при настройке драйвера в фикстуре. Если это неявное ожидание включено, то селениум будет каждый раз при поиске любого элемента ожидать его появления заданное количество секунд.

2022-08-25 11:47 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +# def add_goods_in_basket():
Если назвать этот тест `test_add_goods_in_basket`, то он отрабатывает, причем хорошо ))
Только нужно еще импортнуть `ActionChains`

2022-08-30 17:34 UTC, tmolofei commented on homework/tatiana_molofei/Homework_21/test_hw_21_02.py
> +# def add_goods_in_basket():
Вроде как исправила

2022-08-31 06:41 UTC, eugene-okulik approved these changes

2022-08-31 06:41 UTC, merged