stassia92_homework21_done
eugene-okulik/QAP-08onl pull request #257
Opened 2022-08-17 22:47 UTC by stassia92

2022-08-25 12:13 UTC, eugene-okulik requested changes

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +def test_2():
Этот тест (и следующие) невозможно запустить отдельно. Он выполнится только в случае если перед ним запущен тест `test_1`

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +def test_2():
Названия тестов должны говорить о том, что они проверяют.

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +    driver.implicitly_wait(5)
Неявное ожидание включается один раз при настройке драйвера. Обычно это делается в фикстуре.

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_2.py
> +    driver.implicitly_wait(5)
Неявное ожидание достаточно включить один раз - и оно будет работать всегда вплоть до момента пока ты не сделаешь `driver.quit()`

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_2.py
> +           'All Buttons Clicked'
Все эти тесты должны были быть одним тестом, в конце которого ты проверяешь что ожидаемый текст появился на странице. Все остальные действия - это всего лишь шаги теста, нет необходимости проверять что очередная кнопка появилась. Нужно просто ее нажимать как только она стала доступна.

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_2.py
> +           'All Buttons Clicked'
Тесты от test_9 до test_11 получились не независимыми. Их невозможно запустить отдельно, так как они зависят от результата работы предыдущего теста.

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_3.py
> +    time.sleep(5)
Этот слип не нужен если включено неявное ожидание.

2022-08-25 12:13 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +def start_now():
Название фикстуры должно говорить о своем назначении. Обычно фикстура создается для того, чтобы появилась возможность пользоваться тем, что возвращается в результате ее работы. Здесь возвращается драйвер. Обычно так и называют фикстуру.

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +driver = webdriver.Chrome(service=serv)
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +    bottom_text = driver.find_element(By.CSS_SELECTOR,
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +def test_2():
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +    driver.implicitly_wait(5)
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_2.py
> +    driver.implicitly_wait(5)
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_2.py
> +           'All Buttons Clicked'
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_3.py
> +    time.sleep(5)
исправила перезалила

2022-08-26 17:48 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework21/test_21_2_1.py
> +def start_now():
исправила перезалила

2022-08-29 06:31 UTC, eugene-okulik approved these changes
Теперь прям красота!

2022-08-29 06:31 UTC, merged