nikolay nazarov: homework 21 completed
eugene-okulik/QAP-08onl pull request #262
Opened 2022-08-21 17:22 UTC by nazarovNV

2022-08-25 12:50 UTC, eugene-okulik requested changes
Поправь ворнинги. Второе - по желанию

2022-08-25 12:50 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_21/test_1.py
> +
При запуске этого теста появляются ворнинги, которые хорошо бы починить
![2022-08-25_15-39](https://user-images.githubusercontent.com/98970620/186666995-6c6aaded-52a2-4e30-bbf3-f9fbd801fe82.png)

2022-08-25 12:50 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_21/test_2.py
> +    @pytest.mark.usefixtures('driver')
такая штука у тебя сработала, потому что ты назначил driver переменной класса. Но вообще такой подход не используется, потому что тебе нужно использовать результат работы фикстуры, которая обычно возвращает драйвер. В этом случае сойдет и так, но в целом, надеюсь ты понимаешь как нужно работать с фикстурой.

2022-08-28 12:35 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_21/test_1.py
> +
Поправил, добавил .ini файл

2022-08-28 13:05 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_21/test_2.py
> +    @pytest.mark.usefixtures('driver')
Убрал класс, сделал просто функции. Фикстуры переместил в файл конфтест

2022-08-29 06:33 UTC, eugene-okulik approved these changes
:+1:

2022-08-29 06:33 UTC, merged