Anastasiya_Botukh_homework_21
eugene-okulik/QAP-08onl pull request #264
Opened 2022-08-21 19:26 UTC by Aisatsanaaa

2022-08-21 19:52 UTC, Aisatsanaaa commented
Не понимаю, чем мой драйвер не угодил?

2022-08-28 10:32 UTC, eugene-okulik requested changes
Кроме того, что в комментах, все остальное хорошо

2022-08-28 10:32 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_21/test_21_homework_tests.py
> +    print('sum')
Ты создала в параметрах переменные `a` и `b`, а в аргументах указала `a_num` и `b_num`, а нужно такие же как в параметрах. Этот тест сейчас отказывается работать

2022-08-28 10:32 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_21/test_markers.ini
> +[pytest]
А этот файл нужно назвать pytest.ini, чтобы настройки, которые в нем сделаны, применились

2022-08-29 06:35 UTC, eugene-okulik approved these changes
:+1:

2022-08-29 06:36 UTC, merged