margarita sokol: homework 21 completed
eugene-okulik/QAP-08onl pull request #267
Opened 2022-08-22 12:05 UTC by MargaritaSKL

2022-08-28 12:01 UTC, eugene-okulik requested changes

2022-08-28 12:01 UTC, eugene-okulik commented on homework/margarita_sokol/Homework_21/test_2_2.py
> +from time import sleep
Если не брать в расчет редкие исключительные ситуации, где без слипа не обойтись, слип даже не должен быть импортирован в фалы тестов.

2022-09-04 18:01 UTC, MargaritaSKL commented
вроде все поправила

2022-09-05 06:02 UTC, eugene-okulik commented on homework/margarita_sokol/Homework_21/test_2_3.py
> +    yield _driver_chrome
Здесь перепутала что написать после yield. Нужно было `_driver`, ну и ниже при закрытии тоже `_driver`

2022-09-05 06:02 UTC, eugene-okulik approved these changes
В целом все хорошо, все поправила :+1:

2022-09-05 06:02 UTC, merged