Varvara Kirylchyk Homework23
eugene-okulik/QAP-08onl pull request #270
Opened 2022-08-23 17:45 UTC by Kirylchyk

2022-09-01 11:25 UTC, eugene-okulik requested changes
Все очень хорошо, аж жалко, что нужно на доработку отправлять. Я понимаю почему ты везде создала файлики `__init__.py` Это рабочий вариант, но есть одна проблема с ним. Если это залить в главную ветку (main), то многое сломается из того, что там уже есть. Поэтому выкручиваться нужно по-другому.
Я там скидывал видео как это обойти. В твоем случае, нужно:
удалить фалы init в папках QAP-08onl, homework, varvara_kirylchyk, varvara_kirylchyk_homework23
Изменить импорты, чтобы они начинались с  pages или locators
Запускать тесты открыв папку varvara_kirylchyk_homework23 как проект.
Я у себя сделал - работает. Если хочешь, я залью эти изменения. Если есть желание поразбираться, то можешь сама все сделать.
Не сказать, что это сильно относится к нашему обучению, т.к. проект с автотестами будет в жизни отдельным проектом, а не папочкой в другом проекте. И тогда этих проблем и близко не возникнет.

2022-09-01 11:28 UTC, eugene-okulik commented
А, ну и там для пайлинта нужно переставить импорты аллюра

2022-09-05 15:58 UTC, Kirylchyk commented
что-то пока руки не доходят, давайте так вмержим

2022-09-07 05:01 UTC, eugene-okulik commented
> что-то пока руки не доходят, давайте так вмержим

ок

2022-09-07 05:01 UTC, eugene-okulik approved these changes

2022-09-07 05:01 UTC, merged