anastatsia_machkova_Homework_21
eugene-okulik/QAP-08onl pull request #271
Opened 2022-08-23 19:19 UTC by machkova98

2022-08-28 12:12 UTC, eugene-okulik requested changes
Все в целом хорошо. Но есть одна проблема из-за которой тесты вообще не запускаются, я обошел это, все проверил. Тебе нужно разобраться только с этой проблемой
![2022-08-28_15-10](https://user-images.githubusercontent.com/98970620/187073604-0f54de62-b642-4436-9150-b4d826f18aba.png)
Если есть вопросы как это починить - спрашивай.

2022-08-30 19:54 UTC, machkova98 commented
я добавила параметр name для this test. Но тогда у меня не работает all_tests ((

2022-08-31 06:55 UTC, eugene-okulik requested changes

2022-08-31 06:55 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_21/test_pytest_10.py
> +@pytest.mark.usefixtures(name='this_test')
Здесь просто нужно сделать вот так:
```
@pytest.mark.usefixtures('this_test', 'all_tests')
```
Названия фикстур нужно указывать в кавычках

2022-08-31 06:55 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_21/test_pytest_10.py
> +def test_1(all_tests):
А вот отсюда убрать `all_tests`

2022-09-01 05:42 UTC, eugene-okulik approved these changes

2022-09-01 05:43 UTC, merged