Tatsiana Malafei added Homework_23
eugene-okulik/QAP-08onl pull request #272
Opened 2022-08-23 20:11 UTC by tmolofei

2022-09-01 12:00 UTC, eugene-okulik requested changes
Здорово у тебя получилось обойти проблему с импортами. И пайтест и пайлинт счастливы.

2022-09-01 12:00 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_23/pom/pages/home_page.py
> +    def switch_to_handle(self):
Этот метод был бы полезен не только для этой страницы. Можно подумать как сделать его чуть более универсальным и вынести его в класс BasePage.
Универсальности в него можно добавить как минимум вот так:
```
def switch_to_handle(self, tab_index):
        tabs = self.driver.window_handles
        self.driver.switch_to.window(tabs[tab_index])
```

2022-09-08 16:26 UTC, tmolofei commented on homework/tatiana_molofei/Homework_23/pom/tests/test_home_page.py
> +    auth_page = AuthPage(driver)
исправила

2022-09-08 16:26 UTC, tmolofei commented on homework/tatiana_molofei/Homework_23/pom/tests/test_home_page.py
> +    auth_page = AuthPage(driver)
исправила

2022-09-08 16:27 UTC, tmolofei commented on homework/tatiana_molofei/Homework_23/pom/tests/test_journal_page.py
> +    home_page.open_journal()
исправила

2022-09-08 16:27 UTC, tmolofei commented on homework/tatiana_molofei/Homework_23/pom/pages/home_page.py
> +    def switch_to_handle(self):
пока не разобралась с этим

2022-09-08 17:28 UTC, tmolofei commented on homework/tatiana_molofei/Homework_23/pom/pages/home_page.py
> +    def switch_to_handle(self):
понял)

2022-09-09 05:59 UTC, eugene-okulik approved these changes
Вот сейчас прям хорошо

2022-09-09 05:59 UTC, merged