Zabello homework 26
eugene-okulik/QAP-08onl pull request #314
Opened 2022-09-02 20:42 UTC by Lanselap1488

2022-09-02 20:45 UTC, Lanselap1488 commented
Блин, ругается на ту же ошибку из мейна) . Кстати, почему-то пайчарм начал ругаться на аллюр и иморт вебдрайвера. Ну знаешь почему?

2022-09-05 06:47 UTC, eugene-okulik commented
> Блин, ругается на ту же ошибку из мейна) . Кстати, почему-то пайчарм начал ругаться на аллюр и иморт вебдрайвера. Не знаешь почему?

Ну я в мейне уже подчистил эту ошибку. Так что скоро перестанет ругаться.
Аллюр и вебдрайвер - возможно, виртуальное окружение слетело у тебя в пайчарме или чота типа того.

2022-09-05 08:50 UTC, eugene-okulik requested changes
С захардкоженными айдишиками тест может работать до тех пор пока кто-то другой кроме тебя не начал пользоваться системой.
Сейчас тесты удаления и изменения не работают.
Ну и у меня вообще не хотело ничего запускаться из-за путей к файлам. Если указываешь какой-то путь к файлам, то нужно путь строить относительно того файла, в котором пишешь код. То как сейчас сделано у тебя - это путь относительно того, где сейчас находится пользователь - а это сложнопредсказуемо. Если прийти в папку `api` и оттуда сделать `pytest -v -s`, то получаешь такое:
```
 FileNotFoundError: [Errno 2] No such file or directory: 'api/utils/create_meme.json'
```

2022-09-06 20:53 UTC, Lanselap1488 commented
Исправил)

2022-09-07 05:06 UTC, eugene-okulik approved these changes

2022-09-07 05:06 UTC, merged