Varvara Kirylchyk Homework26
eugene-okulik/QAP-08onl pull request #315
Opened 2022-09-02 21:01 UTC by Kirylchyk

2022-09-06 06:08 UTC, eugene-okulik requested changes

2022-09-06 06:08 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework26/test_varvara_kirylchyk_homework26.py
> +    assert response['text'] == 'Varvara meme updated'
После вот этого теста нужно вернуть мем в исходное состояние. Можно это сделать написав здесь после ассерта код, который это делает, а можно создать функцию называющуюся например `rollback_changes` и вызывать ее после ассерта. Можно даже создать фикстуру, у которой не будет части, которая выполняется перед тестом, но будет часть, которая выполняется после теста - и в этой части возвращает мем в исходное состояние.

2022-09-06 06:08 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework26/test_varvara_kirylchyk_homework26.py
> +    assert len(response) == 1
Здесь, ты, похоже, не поняла задание. Тебе нужно запросить все мемы и проверить есть ли хоть в одном меме тэг fun

2022-09-07 01:13 UTC, Kirylchyk commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework26/test_varvara_kirylchyk_homework26.py
> +    assert response['text'] == 'Varvara meme updated'
что-то не нахожу как сделать, чтобы мем вернулся в исходное состояние. есть rollback(), но это вроде только для db

2022-09-07 05:20 UTC, eugene-okulik requested changes

2022-09-07 05:20 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework26/test_varvara_kirylchyk_homework26.py
> +    assert response['text'] == 'Varvara meme updated'
Нужно написать код, который изменяет мем. Т.е., например, перед выполнением теста сохраняешь куда-нибудь в переменную все содержимое мема, изменяешь мем с помощью PUT запроса, проверяешь, что все сработало, а в конце теста, после того как все проверено пишешь код который снова изменяет мем, чтобы он имел то же содержимое, что имел в начале теста.
Про rollback - я имел ввиду, что все эти действия можно вынести в отдельную функцию, которую можно назвать `rollback` или `rollback_changes`, но в данном случае это не сильно нужно, так как тебе эту операцию нужно сделать всего один раз. Ну и можно это сделать фикстурой, но это не имеет особого смысла здесь, как и функция.

2022-09-07 05:20 UTC, eugene-okulik commented on homework/varvara_kirylchyk/varvara_kirylchyk_homework26/test_varvara_kirylchyk_homework26.py
> +    req.add_header('Authorization', '255a5I8vj9gKF5Z')
И еще ты используешь один и тот же токен, а в задании я писал что "Токены периодически очищаются. Тот токен который был получен вчера, скорее всего не будет работать сегодня."
И вот это произошло. Токены очистились.

2022-09-08 05:34 UTC, eugene-okulik approved these changes

2022-09-08 05:43 UTC, merged