stassia92 homework25 done
eugene-okulik/QAP-08onl pull request #316
Opened 2022-09-03 14:49 UTC by stassia92

2022-09-05 06:33 UTC, eugene-okulik requested changes

2022-09-05 06:33 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/Homework25/homework25.py
> +          f"He has {len(res['children'])} kid(s). "
Забыла перечислить детей )) Сейчас так:
```
User name is John. He lives in New York. He has 2 kid(s). He owns car Dodge, computer Apple.
```
а нужно, например, так:
```
User name is John. He lives in New York. He has 2 kid(s): Hanna and Peter. He owns car Dodge, computer Apple.
```

2022-09-05 09:13 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/Homework25/homework25.py
> +          f"He has {len(res['children'])} kid(s). "
исправила

2022-09-06 06:10 UTC, eugene-okulik approved these changes

2022-09-06 06:10 UTC, merged