Anastasiya_Botukh_Homework_25
eugene-okulik/QAP-08onl pull request #320
Opened 2022-09-04 17:16 UTC by Aisatsanaaa

2022-09-05 06:45 UTC, eugene-okulik requested changes

2022-09-05 06:45 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_25/read_json_ht.py
> +          f"{len(analysed_info['children'])} children. He owns {user_own}.")
Забыла перечислить детей ))
Сейчас так:
```
User name is John, he lives in New York. He has 2 children. He owns car Dodge, computer Apple.
```
а надо, например, так:
```
User name is John, he lives in New York. He has 2 children: Hanna and Peter. He owns car Dodge, computer Apple.
```

2022-09-05 08:07 UTC, Aisatsanaaa commented on homework/Anastasiya_Botukh/Homework_25/read_json_ht.py
> +          f"{len(analysed_info['children'])} children. He owns {user_own}.")
я не забыла про детей, они у меня из-за списка не получались и я так залила))

преобразование списков в словари вспомнила, детей добавила)

2022-09-06 06:13 UTC, eugene-okulik approved these changes

2022-09-06 06:14 UTC, merged