Sergey zhachek homework 26
eugene-okulik/QAP-08onl pull request #324
Opened 2022-09-05 15:07 UTC by SiarheiZhachek

2022-09-05 22:14 UTC, SiarheiZhachek commented
я тут с гитом немного поигрался

2022-09-12 06:59 UTC, eugene-okulik requested changes

2022-09-12 06:59 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_26/test_meme.py
> +    token = token_file.read()
Ты круто сделал, что создал отдельный файл для хранения токена. Но только сейчас он у тебя всегда хранится один и тот же. Сейчас он уже не работает.
Ты можешь сделать фикстуру, которая проверяет валидел ли все еще токен. И если он еще валиден - возвращает его, а если не валиден, то запрашивает новый, записывает в файл и возвращает.

2022-09-12 06:59 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_26/test_meme.py
> +    assert response["text"] == 'What you will see is called a meme, cool memes!!!.'
Здесь ты изменяешь мем, который всегда существует. Для того, чтобы этот тест всегда имел смысл, нужно после теста возвращать мем в то состояние, которое у него было до теста. А то в следующий раз когда ты запустишь тест, в меме ничего не поменяется, так как он уже изначально будет иметь такое содержание, как то, на которое ты меняешь.

2022-09-12 19:45 UTC, SiarheiZhachek commented
исправил

2022-09-15 05:07 UTC, eugene-okulik approved these changes

2022-09-15 05:07 UTC, eugene-okulik commented on homework/siarhei_zhachek/homework_26/conftest.py
> +    token_file.close()
можно было не закрывать. Когда ты работаешь с файлом через менеджер контекста (with...), то файл автоматически закрывается сразу после того как выполнилось все что находится в этом блоке with

2022-09-15 05:08 UTC, merged