Tatsiana Malafei Homework_27 done
eugene-okulik/QAP-08onl pull request #327
Opened 2022-09-06 21:26 UTC by tmolofei

2022-09-07 06:13 UTC, eugene-okulik requested changes
Я там почистил базу, чтобы не было дубликатов одного и того же

2022-09-07 06:13 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_27/hw_27.py
> +
Ты делаешь запросы данных сразу после того как их добавила, но это работает неправильно. Т.к., например, ты добавила студента с group_id = null. В результате, у твоего студента нет группы. Хотя, вижу, запрос студента ты пыталась сделать правильный, но там проблема в том, что в переменной `ID_TOM_22` хранится `None`. Ну и группу ты выбираешь не по `group_id`, имеющуюся у студента. Если после всех инсертов сделать запрос на получение всех данных по Messi, то получается так:
![2022-09-07_09-09](https://user-images.githubusercontent.com/98970620/188801730-8efe6093-faf6-44ee-b749-900939e28c51.png)

2022-09-08 20:49 UTC, tmolofei commented on homework/tatiana_molofei/Homework_27/hw_27.py
> +
вроде как все исправлено

2022-09-09 06:04 UTC, eugene-okulik approved these changes
Да, все исправлено. Теперь работает хорошо

2022-09-09 06:04 UTC, merged