hw26 is done
eugene-okulik/QAP-08onl pull request #331
Opened 2022-09-07 22:15 UTC by stassia92

2022-09-08 06:15 UTC, eugene-okulik requested changes
Красиво все, конечно. Видна рука профессионала ))

2022-09-08 06:15 UTC, eugene-okulik commented on homework/Anastacia_Kuznetcova/hw26/tests/test_hw26.py
> +    assert len(res.json()['data']) > 0 and res.status_code == 200
Этот тест должен был проверить, что существует хотя бы один мем с тэгом `fun`, а ты проверяешь, что ответ от сервера не пустой.

2022-09-08 07:03 UTC, stassia92 commented on homework/Anastacia_Kuznetcova/hw26/tests/test_hw26.py
> +    assert len(res.json()['data']) > 0 and res.status_code == 200
исправила

2022-09-12 06:44 UTC, eugene-okulik approved these changes

2022-09-12 06:47 UTC, merged