Anastasiya_Botukh_Homework_3
eugene-okulik/QAP-08onl pull request #36
Opened 2022-06-01 20:24 UTC by Aisatsanaaa

Я удалила старую ветку и создала новую. А то запуталась там.

2022-06-02 07:12 UTC, eugene-okulik requested changes
И, если несложно, переименуй папку Anastasiya_Botukh_Homework_3 в homework_3

2022-06-02 07:12 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Anastasiya_Botukh_Homework_3/ex_2.py
> +
Осталось удалить вот эту строку и все будет ок

2022-06-05 08:41 UTC, eugene-okulik reviewed
Все хорошо. Один коммент только про лишние переменные. Но это не критично. Если хочешь, можешь поправить.

2022-06-05 08:41 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_3/ex_1.py
> +print(C)
Так как переменной "C" ты пользуешься всего один раз, то можно не создавать эту переменную. Т.е. можно сразу делать так:
```
print(A + B)
```

2022-06-05 10:57 UTC, Aisatsanaaa commented on homework/Anastasiya_Botukh/Homework_3/ex_1.py
> +print(C)
поняла? спасибо! я тогда здесь уже не буду исправлять, но на будущее запомню :)

2022-06-06 11:42 UTC, eugene-okulik approved these changes

2022-06-06 11:42 UTC, merged