Tatiana molofei homework 4 done
eugene-okulik/QAP-08onl pull request #48
Opened 2022-06-03 07:08 UTC by tmolofei

2022-06-03 07:42 UTC, tmolofei commented
У меня есть парочка вопросов по домашке:
1. В задании 4 почему необходимо использовать break, почему нельзя использовать условие while-else? я проверяла и при использовании else, все работала замечательно. Может есть особенности какие?
2. Почему все же все переменные необходимо именовать как UPPER_CASE?
3. В задании 1 я сделала таким образом, что оно работает только при тексте, которые введен, т.к. я принудительно заменяла определенные символы (, и .), но если ввод будет через пользователя, я так понимаю необходимо иначе все прописывать?

2022-06-07 09:00 UTC, eugene-okulik requested changes

2022-06-07 09:00 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_4/hw_04_04.py
> +print("Поздравляю! Вы угадали!")
А я нашел багу. Вот как я поиграл:
```
Попробуйте угадать загаданную цифру. Введите любую цифру 90
Попробуйте снова
Попробуйте угадать загаданную цифру. Введите любую цифру 90
Поздравляю! Вы угадали!
```

2022-06-07 09:00 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_4/hw_04_01.py
> +TEXT_1 = 'ing '.join(my_list)
:+1:

2022-06-07 09:02 UTC, eugene-okulik commented
> У меня есть парочка вопросов по домашке:
> 
> 1. В задании 4 почему необходимо использовать break, почему нельзя использовать условие while-else? я проверяла и при использовании else, все работала замечательно. Может есть особенности какие?
> 2. Почему все же все переменные необходимо именовать как UPPER_CASE?
> 3. В задании 1 я сделала таким образом, что оно работает только при тексте, которые введен, т.к. я принудительно заменяла определенные символы (, и .), но если ввод будет через пользователя, я так понимаю необходимо иначе все прописывать?

С первым и вторым вопросами вроде бы разобрались на занятии
По поводу третьего - все правильно сделала. Для конкретного текста это и нужно было делать.

2022-06-07 09:39 UTC, tmolofei commented on homework/tatiana_molofei/Homework_4/hw_04_04.py
> +print("Поздравляю! Вы угадали!")
исправила)

2022-06-07 15:26 UTC, eugene-okulik approved these changes

2022-06-08 05:53 UTC, tmolofei commented on homework/tatiana_molofei/Homework_4/hw_04_04.py
> +    user_num = int(input('Попробуйте угадать загаданную цифру. Введите любую цифру '))
Спасибо, я учту этот момент :)

2022-06-08 11:26 UTC, merged