Artyom_zabello_homework 4
eugene-okulik/QAP-08onl pull request #51
Opened 2022-06-03 10:03 UTC by Lanselap1488

2022-06-08 11:29 UTC, eugene-okulik commented on homework/artyom_zabello/Homework_4/task3.py
> +symbols(TEXT)
Я сходил и почитал что об этом говорят математики. Одни говорят, что ноль кратен всему, другие говорят, что он не кратен ничему )). Так что пусть остается

2022-06-08 23:08 UTC, Lanselap1488 commented on homework/artyom_zabello/Homework_4/task3.py
> +    print(text[42:46])
Исправил этот момент и вычислением середины)

2022-06-08 23:08 UTC, Lanselap1488 commented on homework/artyom_zabello/Homework_4/task4.py
> +guessing(NUM)
Да просто мне нравится функциями писать, но окей, я понял , без надобности так лучше не делать)

2022-06-09 07:52 UTC, Lanselap1488 commented on homework/artyom_zabello/Homework_4/task1.py
> +    return print(lst)
Исправил)

2022-06-09 08:58 UTC, eugene-okulik requested changes

2022-06-09 08:58 UTC, eugene-okulik commented on homework/artyom_zabello/Homework_4/task1.py
> +                 replace("'", "").replace(",", ""))
Во-первых, можно было использовать `join`, а не вот это вот всё.
А во-вторых, точки с запятыми должны были остаться.

2022-06-10 07:22 UTC, eugene-okulik approved these changes

2022-06-10 07:22 UTC, merged