homework_4 done
eugene-okulik/QAP-08onl pull request #55
Opened 2022-06-03 18:13 UTC by nazarovNV

Сделал четвертую домашнюю работу.

2022-06-07 16:09 UTC, eugene-okulik requested changes

2022-06-07 16:09 UTC, eugene-okulik commented on homework/nikolay_nazarov/Homework_4/task_4.py
> +ANSWER = 0
Вот эта переменная лишняя, а в целом все ок.

2022-06-08 11:49 UTC, nazarovNV commented on homework/nikolay_nazarov/Homework_4/task_3.py
> +print(SOME_TEXT[4::4])
Поправил.

2022-06-08 12:15 UTC, eugene-okulik approved these changes
Классно называешь коммиты. Очень удобно проверять

2022-06-08 12:16 UTC, merged