Anastasiya botukh howemork 4
eugene-okulik/QAP-08onl pull request #62
Opened 2022-06-05 19:22 UTC by Aisatsanaaa

Пока что без 1-ого задания. Чуть позже добавлю.

2022-06-08 12:23 UTC, eugene-okulik requested changes
См. комменты. Ну и куда-то подевалось первое задание

2022-06-08 12:23 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_4/exercise_2.py
> +    print('Yes, this string contains this word!')
А что же написало бы если бы этого слова не было в тексте?

2022-06-08 12:23 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_4/exercise_3.py
> +MY_LIST_2 = TEXT[40:44]
В целом сойдет, но можно было вычислять в коде где у строки центр.

2022-06-08 12:23 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_4/exercise_4.py
> +    print("Sorry, no. Try again")
Нашел баг. Вот так поиграл (внимание на последнюю строку):
```
Please, try to guess the secret number:90
Sorry, no. Try again
Please, try to guess the secret number:12
Congratulations! It's right number.
Sorry, no. Try again
```
Если сильно не запорачиваться, это можно починить добавлением `break`

2022-06-08 15:24 UTC, Aisatsanaaa commented on homework/Anastasiya_Botukh/Homework_4/exercise_3.py
> +MY_LIST_2 = TEXT[40:44]
я попробовала, но что-то не дошло, как это сделать. сможете показать на занятии завтра?

2022-06-08 16:17 UTC, Aisatsanaaa commented on homework/Anastasiya_Botukh/Homework_4/exercise_4.py
> +    print("Sorry, no. Try again")
исправила

2022-06-09 08:59 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_4/exercise_3.py
> +MY_LIST_2 = TEXT[40:44]
Да, не вопрос

2022-06-09 09:15 UTC, merged