Tatiana molofei homework 5 task 1-3 done
eugene-okulik/QAP-08onl pull request #65
Opened 2022-06-06 22:04 UTC by tmolofei

2022-06-07 08:40 UTC, tmolofei commented
Евгений)

Вопрос опять тот же:
1) в задании 4 мне насильно приходится прерывать цикл if через break, иначе к значению "salary' добавляет не 500, а 1000. И я пока не могу понять почему, т.к. мы выполняем эту команду только один раз т.к. 'title' = 'head' в словаре только один.

2022-06-10 07:50 UTC, eugene-okulik requested changes
В целом все хорошо. Можно поработать немного над красотой

2022-06-10 07:50 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_5/hw_05_03.py
> +print(f'"{NEW_STRING}", "b" == {NEW_STRING.count(LETTER)}')
"b" можно было тоже не писать в тексте. Ведь она у тебя хранится в переменной.

2022-06-10 07:50 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_5/hw_05_04.py
> +print(departments)
Все хорошо, но старайся давать переменным более осмысленные имена. Например, здесь можно было сделать так:
```
for department, people in departments.items():
    for person, data in people.items():
```
Уже сложновато, но если добавить к этому еще один уровень key2, value2, то рискуешь вообще не разобраться что к чему.

2022-06-10 14:34 UTC, tmolofei commented on homework/tatiana_molofei/Homework_5/hw_05_04.py
> +print(departments)
Согласна, запутаться будет легко) Внесла изменения

2022-06-11 06:56 UTC, eugene-okulik approved these changes

2022-06-11 06:56 UTC, merged