Wolk sergey
eugene-okulik/QAP-08onl pull request #68
Opened 2022-06-07 15:11 UTC by Sergey1991wolk

2022-06-08 12:46 UTC, eugene-okulik requested changes

2022-06-09 07:47 UTC, Sergey1991wolk commented on homework/wolk/wolk_sergey_homework_4/homework_4/hwork_4.py
> +    print("Поздравляю! Вы угадали!")
Исправил  закоммитил и запушил

2022-06-09 07:47 UTC, Sergey1991wolk commented on homework/wolk/wolk_sergey_homework_4/pract_4/pract_3.py
> +print(MY_NAME)
Переделал

2022-06-09 09:25 UTC, eugene-okulik approved these changes

2022-06-09 09:27 UTC, merged