andrei ananich: homework 4 completed
eugene-okulik/QAP-08onl pull request #71
Opened 2022-06-07 20:58 UTC by AndreiQA

2022-06-08 12:55 UTC, eugene-okulik requested changes

2022-06-08 12:55 UTC, eugene-okulik commented on homework/andrei_ananich/homework_4/homework_4_3.py
> +print(A[43:47])
Круто было бы вычислить где середина и исходя из этого достать срез.

2022-06-08 12:55 UTC, eugene-okulik commented on homework/andrei_ananich/homework_4/homework_4_4.py
> +TEXT = int(input('Угадайте число. Введите цифру'))
За такое название переменной тебя бы прирезал тот, кто залез бы после тебя изменить этот код. Числовая переменная с названием text )))

2022-06-08 12:55 UTC, eugene-okulik commented on homework/andrei_ananich/homework_4/homework_4_3.py
> +print(len(A)/2)
А это чо ты делаешь?

2022-06-08 18:01 UTC, AndreiQA commented on homework/andrei_ananich/homework_4/homework_4_4.py
> +TEXT = int(input('Угадайте число. Введите цифру'))
я бы сам так поступил с таким кодером))

2022-06-08 18:03 UTC, AndreiQA commented on homework/andrei_ananich/homework_4/homework_4_3.py
> +print(A[43:47])
done

2022-06-09 09:30 UTC, eugene-okulik approved these changes

2022-06-09 09:30 UTC, merged