Homework 5 is done
eugene-okulik/QAP-08onl pull request #75
Opened 2022-06-09 08:26 UTC by Lanselap1488

2022-06-11 07:48 UTC, eugene-okulik requested changes

2022-06-11 07:48 UTC, eugene-okulik commented on homework/artyom_zabello/homework5/work2.py
> +print(f"{SALARY},{BONUS} == ${NEW_SALARY}")
Прикольно

2022-06-11 07:48 UTC, eugene-okulik commented on homework/artyom_zabello/homework5/work4.py
> +print(departments)
Если добавить еще один отдел, то его начальнику ты не насыпешь побольше бабла.
И старайся использовать более осмысленные имена переменных. Вместо `i, x` можно было сделать `person, data`, например

2022-06-15 12:24 UTC, eugene-okulik requested changes

2022-06-15 12:24 UTC, eugene-okulik commented on homework/artyom_zabello/homework5/work4.py
> +print(departments)
Будешь исправлять это? Или забил?

2022-06-15 18:13 UTC, Lanselap1488 commented on homework/artyom_zabello/homework5/work4.py
> +print(departments)
Исправил) быстро получилось, странно что сразу не допер что так можно сделать

2022-06-18 08:29 UTC, eugene-okulik approved these changes

2022-06-18 08:29 UTC, merged