Tatiana molofei homework 6 (task 1-2)
eugene-okulik/QAP-08onl pull request #79
Opened 2022-06-09 23:01 UTC by tmolofei

2022-06-10 12:26 UTC, eugene-okulik requested changes

2022-06-10 12:26 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_6/hw_06_01.py
> +user_string()
А если STRING = "abeehhhhhccced", то твоя программа не работает

2022-06-10 15:17 UTC, tmolofei commented on homework/tatiana_molofei/Homework_6/hw_06_01.py
> +user_string()
Исправила, вроде как работает не только с буквами, но и символами

2022-06-11 08:50 UTC, eugene-okulik requested changes

2022-06-11 08:50 UTC, eugene-okulik commented on homework/tatiana_molofei/Homework_6/hw_06_01.py
> +print(RESULT)
неа. для строки "abeehhhhhccced" результат должен быть "abe2h5c3ed", а у тебя "a1b1e3h5c3d1"

2022-06-15 13:49 UTC, eugene-okulik commented
Как дела?

2022-06-15 16:41 UTC, tmolofei commented
Вроде и ничего)
Сегодня загружу остальную домашку)

2022-06-15 16:44 UTC, tmolofei commented
По task 1 есть вопрос: 
user_str = f'{input()} ' - я принудительно добавила вот тут пробел в конце текста, иначе у меня код пропускал последний символ из строки и ничего с ним не выполнял) я может еще попробую иначе переписать его)

2022-06-15 17:00 UTC, eugene-okulik requested changes
Первое и второе задание - ок.
Жду третье

2022-06-15 18:42 UTC, tmolofei commented
готово

2022-06-18 08:34 UTC, eugene-okulik approved these changes

2022-06-18 08:34 UTC, merged