anastasia_machkova_homework_5_done
eugene-okulik/QAP-08onl pull request #81
Opened 2022-06-10 07:45 UTC by machkova98

2022-06-11 08:35 UTC, eugene-okulik requested changes

2022-06-11 08:35 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_5/task_1.py
> +        print(i)
Немного нарушена последовательность `if`ов и `elif`ов. В целом все условия правильные, но условие `elif i % 3 == 0 and i % 5 == 0` никогда не отработает, т.к. оно объединяет два предыдущих условия.

2022-06-11 08:35 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_5/task_2.py
> +    print(A)
Идея была в том, что `salary` и `bonus` может поменять пользователь (ну, типа зайти в код и поменять значения переменных), а программа на основании значения `bonus` увеличивает или не увеличивает `salary`
Ну и переменным лучше давать говорящие имена. A и B очень плохо воспринимаются в коде, а `salary` и `bonus` вполне понятны

2022-06-11 08:35 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_5/task_2.py
> +    print(A)
Идея была в том, что `salary` и `bonus` может поменять пользователь (ну, типа зайти в код и поменять значения переменных), а программа на основании значения `bonus` увеличивает или не увеличивает `salary`
Ну и переменным лучше давать говорящие имена. A и B очень плохо воспринимаются в коде, а `salary` и `bonus` вполне понятны

2022-06-11 08:35 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_5/task_4.py
> +print(departments)
Все хорошо, но старайся давать переменным более осмысленные имена. Например, здесь можно было сделать так:
```
for department, people in departments.items():
    for person, data in people.items():
```
Уже сложновато, но если добавить к этому еще один уровень key3, value3, то рискуешь вообще не разобраться что к чему.

2022-06-11 08:35 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_5/task_4.py
> +print(departments)
Все хорошо, но старайся давать переменным более осмысленные имена. Например, здесь можно было сделать так:
```
for department, people in departments.items():
    for person, data in people.items():
```
Уже сложновато, но если добавить к этому еще один уровень key3, value3, то рискуешь вообще не разобраться что к чему.

2022-06-15 12:27 UTC, eugene-okulik commented
А задание все еще ждет твоих исправлений

2022-06-18 12:07 UTC, machkova98 commented on homework/Anastasia_Machkova/Homework_5/task_2.py
> +    print(A)
Спасибо за комментарии. Сегодня вечером исправлю 5  и 6 домашки.

2022-06-21 15:45 UTC, eugene-okulik approved these changes

2022-06-21 15:46 UTC, merged