anastasiya_botukh_homework_6
eugene-okulik/QAP-08onl pull request #84
Opened 2022-06-11 12:06 UTC by Aisatsanaaa

3 задание позже сделаю

2022-06-11 12:24 UTC, Aisatsanaaa commented
Гит хочет, чтобы я убрала value? но у меня без value не работает((

2022-06-12 09:24 UTC, eugene-okulik requested changes
См. комменты, ну и третьего задания еще не хватает

2022-06-12 09:24 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_1.py
> +    for key, value in enumerate(user_str):
Во-первых, у тебя это не key, value, а index, element.
Во-вторых, ты действительно не используешь вторую переменную. Тебе нужен только порядковый номер. А его можно получить с помощью:
```
for i in range(0, len(user_str):
```

2022-06-12 09:24 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_2.py
> +print(*ACTIONS.split(), sep='\n')
:+1:

2022-06-12 09:24 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_2.py
> +    return num_1 // num_2, num_1 % num_2
результат деления 3/2 мне выдало 1.5, а должно было 1 и 1 (частное и остаток)

2022-06-12 16:25 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_1.py
> +    for key, value in enumerate(user_str):
Игнорь мое предложение использовать range. На это pylint тоже ругается. Короче, тут подход такой: в случаях, когда какую-то переменную нужно создать, но не нужно использовать, переменную называют "_". Т.е. у тебя это будет:
```
for key, _ in enumerate(user_str):
```
Такой подход палинту нравится

2022-06-12 17:15 UTC, Aisatsanaaa commented on homework/Anastasiya_Botukh/Homework_6/ht_2.py
> +    return num_1 // num_2, num_1 % num_2
я не так поняла, видимо, потому что у меня было отдельно деление и отдельно частное и остаток...)))

2022-06-13 19:15 UTC, Aisatsanaaa commented
3-ее добавила

2022-06-15 13:49 UTC, eugene-okulik requested changes

2022-06-15 13:49 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_3.py
> +print(DICT)
Осталось вот эту часть:
```
for value1, value2 in zip(EVEN, ODD):
    DICT[value1] = int(value2.replace('р', ''))
```
оформить как генератор - и все будет ок

2022-06-15 13:49 UTC, eugene-okulik commented on homework/Anastasiya_Botukh/Homework_6/ht_2.py
> +    return num_1 // num_2, num_1 % num_2
Если выбрать action 10, то орабатывает деление.
Надо чтобы или ничего не отрабатывало  при вводе несуществующего действия, или чтобы программа говорила, что такого действия не предусмотрено.

2022-06-18 08:46 UTC, eugene-okulik approved these changes

2022-06-18 08:46 UTC, merged