varvara_kirylchyk_homework_06_done
eugene-okulik/QAP-08onl pull request #85
Opened 2022-06-11 19:41 UTC by Kirylchyk

2022-06-15 13:57 UTC, eugene-okulik requested changes

2022-06-15 13:57 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_02.py
> +print(func_res)
Не забудьте о проверке деления на 0

2022-06-15 13:57 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_02.py
> +print(func_res)
Валидации ты посоздавала, но забыла использовать

2022-06-15 13:57 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_03.py
> +
Все хорошо, но переделай этот for в виде генератора

2022-06-15 16:32 UTC, Kirylchyk commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_02.py
> +print(func_res)
что-то не улавливаю

Если выбираю деление и второе число 0 -> получаю ошибку 

```
if not validate_zero(C):
    raise Exception("Деление на ноль")
```

вроде работает...

2022-06-15 17:05 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_02.py
> +print(func_res)
А, ну я поступил как обычный пользователь - испугался ексепшена.
Не кидайся в пользователя эксепшенами. Они начинают думать, что ничо не работает. Эксепшен - это обычно знак того, что случилось что-то к чему программист не подготовился. А тут ты прям специальную валидацию сделала. Можно и красиво пользователю написать что он делает не так. Эксепшены можно рейзить когда ты знаешь, что твоей программой будут пользоваться только через другую программу. А вот общение между программами с помощью эксепшенов - нормальное дело.

2022-06-15 17:07 UTC, eugene-okulik requested changes

2022-06-15 17:07 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_03.py
> +    print(keys, values)
А, ну и этот for тоже

2022-06-15 17:09 UTC, Kirylchyk commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_03.py
> +    print(keys, values)
не правильно? не понимаю, как надо....

2022-06-15 17:12 UTC, Kirylchyk commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_02.py
> +print(func_res)
я нагуглила exeption и понравилось, решила добавить))) хорошо, поняла, переделаю

2022-06-15 17:15 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_03.py
> +    print(keys, values)
А, ну тут я промазал - тут ты просто принтаешь в цикле

2022-06-15 17:17 UTC, eugene-okulik commented on homework/varvara_kirylchyk/homework06/varvara_kirylchyk_hm_06_03.py
> +
генератор это когда ты вместо
```
my_list2 = []
for i in my_list:
   my_list2.append(i)
```
делаешь вот такую штуку:
```
my_list2 = [i for i in my_list]
```

2022-06-18 08:49 UTC, eugene-okulik approved these changes

2022-06-18 08:49 UTC, merged