Artyom zabello homework 6
eugene-okulik/QAP-08onl pull request #87
Opened 2022-06-12 12:41 UTC by Lanselap1488

Не убрал замечание пайлинта в первом задании, потому что с enumerate пока не получается сделать.

2022-06-12 16:51 UTC, eugene-okulik requested changes

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func1.py
> +    for i in range(len(word)):
Тут все просто:
```
for i, _ in enumerate(word):
```
Переменную "_" создают когда переменную создать почему-то надо, но использовать ее не планируется

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func1.py
> +print(word_counter(input()))
Для строки "abehhhhhccceed" работает неправильно. Результат должен быть "abeh5c3e2d", а сейчас получается "abe2h5c3d"

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func2.py
> +            print("Не правильная операция, попробуйте еще раз")
:+1:

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func3.py
> +print(dict_gen())
Идея была в том, что весь процесс конвертации будет сделан с помощью генераторов.
Ну и цены у тебя не int в результате.

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func3.py
> +print(dict_gen())
Подсказка - перенос строки - отличный разделитель, которым можно пользоваться при `split`.

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func3.py
> +print(dict_gen())
Хотя, если присмотреться, у тебя проблема не с разделением. Ваще не понимаю что здесь происходит. 
```
for i in RES:
        if not i.isalpha():
            for x_1 in i:
                if x_1 == "р":
                    LST.append(i.replace(x_1, ""))
        elif i.isalpha():
            LST.append(i)
```
Осмысленные названия переменных помогли бы. Если это ты так избавляешься от буквы "р", то это делается с помощью `some_string.replace('р', '')`

2022-06-12 16:51 UTC, eugene-okulik commented on homework/artyom_zabello/homework_6/func3.py
> +print(dict_gen())
И кстати ты мне подсказал простое решение в две строчки. Одна из строк такая же как у тебя:
```
RES = PRICE_LIST.split()
```
А вторая тоже твоя, но немного измененная. Вот эта:
```
{LST[i]: LST[i + 1] for i in range(0, len(LST), 2)}
```
Только итерируешься не по LST, а по RES, ну и по пути избавляешся от "р", и превращаешь в int

2022-06-15 14:04 UTC, eugene-okulik requested changes

2022-06-15 18:55 UTC, Lanselap1488 commented on homework/artyom_zabello/homework_6/func1.py
> +print(word_counter(input()))
Поправил, тепер и с этими входными работает, вроде получше, но все равно коряво)

2022-06-15 21:53 UTC, Lanselap1488 commented on homework/artyom_zabello/homework_6/func3.py
> +print(dict_gen())
Исправил, я не игнорил, просто временни не было)

2022-06-18 09:00 UTC, eugene-okulik approved these changes

2022-06-18 09:00 UTC, merged