anastasia_machkova_homework_6_done
eugene-okulik/QAP-08onl pull request #94
Opened 2022-06-15 11:38 UTC by machkova98

2022-06-15 14:31 UTC, eugene-okulik requested changes

2022-06-15 14:31 UTC, eugene-okulik commented on homework/Anastasia_Machkova/Homework_6/task_3.py
> +print({k: int(v[:-1]) for k, v in PAIRS})
Красота какая
`split(" ")` можно заменить на `split()` - разделение по пробелу - значение по умолчанию для этой функции

2022-06-18 09:03 UTC, eugene-okulik commented
Как дела? Будешь исправлять?

2022-06-20 08:24 UTC, machkova98 commented on homework/Anastasia_Machkova/Homework_6/task_1.py
> +print(enum("abeehhhhhccced"))
это я не буду исправлять, что-то не доходит)

2022-06-21 15:49 UTC, eugene-okulik approved these changes
Ну, не страшно. Главное, что поковырялась - это тоже опыт.

2022-06-21 15:49 UTC, merged