margarita sokol: homework 6 completed
eugene-okulik/QAP-08onl pull request #98
Opened 2022-06-15 20:07 UTC by MargaritaSKL

2022-06-18 09:06 UTC, eugene-okulik requested changes
Пока что я саму домашку не смотрел. Поправь для начала все, на что ругается Pylint. Если где-то не понимаешь что нужно исправить - спрашивай.

2022-06-18 13:38 UTC, MargaritaSKL commented
вроде поправила, только не совсем понимаю, как в 3 задаче устранить проблему.

`homework/margarita_sokol/Homework_6/task3.py:25:13: R1721: Unnecessary use of a comprehension, use dict(LIST) instead. (unnecessary-comprehension)`

2022-06-18 17:16 UTC, eugene-okulik commented
> вроде поправила, только не совсем понимаю, как в 3 задаче устранить проблему.
> 
> `homework/margarita_sokol/Homework_6/task3.py:25:13: R1721: Unnecessary use of a comprehension, use dict(LIST) instead. (unnecessary-comprehension)`

Это он тебе говорит, что лучше не использовать в этом месте генератор. Мне не очень понятно почему. Возможно, это от того, что слешком простой генератор - и  поэтому его можно было написать по-другому. Но там есть еще что можно поправить, и, возможно, конкретно этот генератор будет не нужен.

2022-06-18 17:17 UTC, eugene-okulik commented on homework/margarita_sokol/Homework_6/task3.py
> +        LIST.append(PAIRS)
Как минимум, эти два `for`а можно заменить генераторами. А там, глядишь, еще меньше кода станет

2022-06-18 17:20 UTC, eugene-okulik requested changes
Поиграйся с генераторами примерно как я показывал на последнем занятии. По идее пайлинт должен перестать ругаться

2022-06-21 15:53 UTC, eugene-okulik approved these changes

2022-06-21 15:53 UTC, merged